version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.3.0
    - 5.8.0
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: arrow
    versions:
    - 0.17.0
  - dependency-name: jinja2
    versions:
    - 2.11.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootstrap
    versions:
    - 4.5.3
