language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r requirements.txt --use-mirrors
before_script:
    - psql -c 'create database flask_bones;' -U postgres
script:
    - coverage run tests.py
after_success:
    - coveralls
