version: "3"
services:
  app:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=serve.py
      - FLASK_DEBUG=True
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/flask-bones
